### ISSUE TITLE
Add Twemojis for a good cause

### ISSUE THREAD

**Issue by apenasigordev** [top-gg/docs#56]
## Just for a good cause, but... I think it's beautiful 😂.

html:
```html
<script src="https://twemoji.maxcdn.com/v/latest/twemoji.min.js" crossorigin="anonymous"></script>
```
js: 
```js
twemoji.parse(document.body)
```
css:
```css
/*Blablabla*/
img.emoji {
width: 1em;
}
```

**I hope this is a good thing... eh... Here I go!**
